{{- $clustername := .Values.cluster.name }}
apiVersion: rke-machine-config.cattle.io/v1
kind: Amazonec2Config
metadata:
  name: {{ $clustername }}-controlplane
  namespace: fleet-default
instanceType: t3a.medium
region: us-east-1
subnetId: subnet-064523a877a20ee8f
vpcId: vpc-0489b97f06e544c65
zone: b
sshUser: ubuntu
